title = "SecureShop Gitleaks Config"

[allowlist]
description = "Global allowlist"
paths = [
    '''go\.sum''',
    '''package-lock\.json''',
    '''yarn\.lock''',
    '''test/''',
    '''docs/''',
    '''.github/''',
]