events {
    worker_connections 1024;
}

http {
    upstream user_service {
        server user-service:8000;
    }
    upstream product_service {
        server product-service:8000;
    }
    upstream order_service {
        server order-service:8000;
    }
    upstream payment_service {
        server payment-service:8000;
    }
    upstream notification_service {
        server notification-service:8000;
    }
    upstream inventory_service {
        server inventory-service:8000;
    }

    server {
        listen 80;
        server_name localhost;

        # User Service
        location /users {
            proxy_pass http://user_service;
        }
        location /register {
            proxy_pass http://user_service;
        }
        location /login {
            proxy_pass http://user_service;
        }

        # Product Service
        location /products {
            proxy_pass http://product_service;
        }

        # Order Service
        location /orders {
            proxy_pass http://order_service;
        }

        # Payment Service
        location /payments {
            proxy_pass http://payment_service;
        }

        # Notification Service
        location /notifications {
            proxy_pass http://notification_service;
        }

        # Inventory Service
        location /inventory {
            proxy_pass http://inventory_service;
        }
    }
}