services:
  gateway:
    build:
      context: ../gateway
    image: secureshop-gateway
    ports:
      - "80:80"
    depends_on:
      - user-service
      - product-service
      - order-service
      - payment-service
      - notification-service
      - inventory-service
    networks:
      - secureshop-network

  user-service:
    build:
      context: ../services/user-service
    image: secureshop-user-service
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=secureshop-dev-token
      # ⚠️ VULNERABLE: Secrets below for Checkov detection
      - JWT_SECRET=supersecretkey123
      - DB_PASSWORD=admin123
    ports:
      - "8001:8000"
    depends_on:
      - vault
    networks:
      - secureshop-network

  product-service:
    build:
      context: ../services/product-service
    image: secureshop-product-service
    ports:
      - "8002:8000"
    networks:
      - secureshop-network

  order-service:
    build:
      context: ../services/order-service
    image: secureshop-order-service
    ports:
      - "8003:8000"
    networks:
      - secureshop-network

  payment-service:
    build:
      context: ../services/payment-service
    image: secureshop-payment-service
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=secureshop-dev-token
      # ⚠️ VULNERABLE: Secrets below for Checkov detection
      - STRIPE_KEY=sk_live_4eC39HqLyjWDarjtT1zdp7dc
      - PAYMENT_DB_PASSWORD=P@ssw0rd2024!
    ports:
      - "8004:8000"
    depends_on:
      - vault
    networks:
      - secureshop-network

  notification-service:
    build:
      context: ../services/notification-service
    image: secureshop-notification-service
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=secureshop-dev-token
      # ⚠️ VULNERABLE: Secrets below for Checkov detection
      - SMTP_PASSWORD=EmailP@ss123
      - SMTP_USER=noreply@secureshop.com
    ports:
      - "8005:8000"
    depends_on:
      - vault
    networks:
      - secureshop-network

  inventory-service:
    build:
      context: ../services/inventory-service
    image: secureshop-inventory-service
    ports:
      - "8006:8000"
    networks:
      - secureshop-network

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_USER: admin
      POSTGRES_DB: secureshop
    ports:
      - "5432:5432"
    networks:
      - secureshop-network

  # ================= HASHICORP VAULT =================
  vault:
    image: hashicorp/vault:1.15
    container_name: vault
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: secureshop-dev-token
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"
    networks:
      - secureshop-network
    command: vault server -dev

networks:
  secureshop-network:
    driver: bridge
